# Generated by Django 3.2.20 on 2023-08-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='authentication.UserProfile'),
        ),
    ]
